### ISSUE TITLE
SPOP: redis-benchmark can't run against garnet

### ISSUE THREAD

**Issue by hagemt** [microsoft/garnet#134]
Uncertain if you want to prioritize this bug, but I think it would help optics around compatibility w.r.t Redis 7.

Reproduction steps:

```
# clone on macOS
docker-compose up -d

# expected:
brew install redis
brew services start redis
redis-benchmark -p 6379

# unexpected result:
redis-benchmark -p 3278
...
Error: Server closed the connection
```

In `docker-compose logs -f` observe:

```
ProcessMessages threw exception System.ArgumentException: Range of random number does not contain at least one possibility.
	at System.Security.Cryptography.RandomNumberGenerator.GetInt32(Int32 fromInclusive, Int32 toExclusive)
	at Garnet.server.SetObject.SetPop(Byte* input, Int32 length, SpanByteAndMemory& output) in /source/libs/server/Objects/Set/SetObjectImpl.cs:line 191
	at Garnet.server.SetObject.Operate(SpanByte& input, SpanByteAndMemory& output, Int64& sizeChange) in /source/libs/server/Objects/Set/SetObject.cs:line 121
	at Garnet.server.StorageSession.RMWObjectStoreOperationWithOutput[TObjectContext](Byte[] key, ArgSlice input, TObjectContext& objectStoreContext, GarnetObjectStoreOutput& outputFooter) in /source/libs/server/Storage/Session/ObjectStore/Common.cs:line 52
	at Garnet.server.StorageSession.SetPop[TObjectContext](Byte[] key, ArgSlice input, GarnetObjectStoreOutput& outputFooter, TObjectContext& objectContext) in /source/libs/server/Storage/Session/ObjectStore/SetOps.cs:line 431
	at Garnet.server.GarnetApi`2.SetPop(Byte[] key, ArgSlice input, GarnetObjectStoreOutput& outputFooter) in /source/libs/server/API/GarnetApiObjectCommands.cs:line 289
	at Garnet.server.RespServerSession.SetPop[TGarnetApi](Int32 count, Byte* ptr, TGarnetApi& storageApi) in /source/libs/server/Resp/Objects/SetCommands.cs:line 392
	at Garnet.server.RespServerSession.ProcessArrayCommands[TGarnetApi](TGarnetApi& storageApi) in /source/libs/server/Resp/RespServerSession.cs:line 376
	at Garnet.server.RespServerSession.ProcessBasicCommands[TGarnetApi](Byte* ptr, RespCommand cmd, TGarnetApi& storageApi) in /source/libs/server/Resp/RespServerSession.cs:line 327
	at Garnet.server.RespServerSession.ProcessMessages() in /source/libs/server/Resp/RespServerSession.cs:line 273
	at Garnet.server.RespServerSession.TryConsumeMessages(Byte* reqBuffer, Int32 bytesReceived) in /source/libs/server/Resp/RespServerSession.cs:line 199
```

It appears some of the code doesn't account for the range [0, 0) which `GetInt32` rejects, see:

- https://github.com/microsoft/garnet/blob/5b6c3ae97e261fca4fefdadf304efe8537d550a6/libs/server/Objects/Set/SetObjectImpl.cs#L191
- https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.randomnumbergenerator.getint32?view=net-8.0

Want me to attempt a PR that patches this? Looks like a bug in the SPOP implementation. https://redis.io/commands/spop/

**Comment by badrishc** [comment]
Thanks for the report, sure we accept contributions, thanks!

**Comment by vazois** [comment]
We fixed the issue with SPOP. Unfortunately, XADD is not supported right now. So running the full benchmark will result in -ERR UNKNOWN COMMAND.
