### ISSUE TITLE
Crashes on primary during snapshotting disk flush

### ISSUE THREAD

**Issue by msft-paddy14** [microsoft/garnet#385]
### Describe the bug

Garnet server crashes in Cluster mode during snapshotting phase-  observed when cache is full (not sure about other cases). This happens when we're trying to flush to disk.

### Steps to reproduce the bug

Setup:
Version: Garnet 1.0.7
Kubernetes Cluster on Linux OS
Flags:
args:
        - '--clean-cluster-config'
        - '--cluster'
        - '--port'
        - '3278'
        - '--aof'
        - '-m'
        - 40g
        - '--tls'
        - '--issuer-certificate-path'
        - /falcon-managed-secrets/ssl-cert.pem.crt
        - '--cert-file-name'
        - /falcon-managed-secrets/ssl-cert.pfx
        - '--cert-password'
        - ''
        - '-s'
        - 1g
        - '-i'
        - 1g
        - '--metrics-sampling-freq'
        - '2'
        - '--latency-monitor'
        - '-c'
        - /var/scratch/data
        - '--aof-commit-freq'
        - '-1'
        - '--fast-commit'
        - '--aof-null-device'
        - '--on-demand-checkpoint'
        - '--main-memory-replication'
        - '--no-obj'
        - '--gossip-sp'
        - '70'
        - '--client-certificate-required'
        - 'false'
        - '--auth'
        - ACL
        - '--acl-file'
        - /var/scratch/config/acl.conf
        - '--logger-level'
        - Trace

Steps for repro:
Cluster setup: 1 primary and 1 secondary
1. Ingest 40GB data into primary
2. Kill Primary and allow secondary to failover.
3. Make new node secondary of the just failed over primary
4. Checkpoint initiated on Primary
5. Crashes while flushing to disk

**Logs just before crash**
```
05::13::32 trce: TsavoriteKV [main][0] Moved to Intermediate (WAIT_INDEX_CHECKPOINT), 3
05::13::32 trce: TsavoriteKV [main][0] Starting async delta log flush with throttling enabled (0ms)
05::13::32 trce: TsavoriteKV [main][0] Moved to WAIT_FLUSH, 3
```
**CRASH** 
```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Tsavorite.core.AllocatorBase`2[[Tsavorite.core.SpanByte, Tsavorite.core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b],[Tsavorite.core.SpanByte, Tsavorite.core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b]].AsyncFlushPageToDeviceCallback(UInt32, UInt32, System.Object)
   at Tsavorite.core.ManagedLocalStorageDevice+<>c__DisplayClass13_0+<<WriteAsync>b__0>d.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Tsavorite.core.ManagedLocalStorageDevice+<>c__DisplayClass13_0+<<WriteAsync>b__0>d, Tsavorite.core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b]].MoveNext(System.Threading.Thread)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean)
   at System.Threading.Tasks.Task.RunContinuations(System.Object)
   at System.Threading.Tasks.ValueTask+ValueTaskSourceAsTask+<>c.<.cctor>b__4_0(System.Object)
   at Microsoft.Win32.SafeHandles.SafeFileHandle+ThreadPoolValueTaskSource.ExecuteInternal()
   at Microsoft.Win32.SafeHandles.SafeFileHandle+ThreadPoolValueTaskSource.System.Threading.IThreadPoolWorkItem.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
```

**Comment by badrishc** [comment]
Fixed in linked PR: https://github.com/microsoft/garnet/pull/390
