### ISSUE TITLE
Bug: `--aof-commit-freq` not working

### ISSUE THREAD

**Issue by Alirexaa** [microsoft/garnet#537]
### Describe the bug

Garnet container with persistent data using bind mount and `--aof-commit-freq` starts with an error and data does not persist frequently.

error:
```
01::53::04 fail: StoreWrapper[0] CommitTask exception received, AOF tail address = 376; AOF committed until address = 376;  System.NullReferenceException: Object reference not set to an instance of an object.    at Garnet.server.StoreWrapper.CommitTask(Int32 commitFrequencyMs, ILogger logger, CancellationToken token) in /src/libs/server/StoreWrapper.cs:line 320
```

### Steps to reproduce the bug

Just run following command:

```
docker run --mount type=bind,source=c:\\tempdata,target=/data  ghcr.io/microsoft/garnet:1.0  "--checkpointdir" "/data/checkpoint" "--recover" "--aof" "--aof-commit-freq" "60000"
```

### Expected behavior

container runs without any errors and data is saved on disk frequently.

### Additional context

Container logs:

```
    _________
   /_||___||_\      Garnet 1.0.15 64 bit; standalone mode
   '. \   / .'      Port: 6379
     '.\ /.'        https://aka.ms/GetGarnet
       '.'

* Ready to accept connections
01::53::04 fail: StoreWrapper[0] CommitTask exception received, AOF tail address = 376; AOF committed until address = 376;  System.NullReferenceException: Object reference not set to an instance of an object.    at Garnet.server.StoreWrapper.CommitTask(Int32 commitFrequencyMs, ILogger logger, CancellationToken token) in /src/libs/server/StoreWrapper.cs:line 320
```

**Comment by badrishc** [comment]
In StoreWrapper.cs line 320,
 
`clusterProvider.IsReplica()`
 
should be
 
`clusterProvider?.IsReplica()`

**Comment by Alirexaa** [comment]
When is the next version release date including this?
