### ISSUE TITLE
Issue with publishing and subscribing

### ISSUE THREAD

**Issue by slqd3781** [microsoft/garnet#804]
### Describe the bug

Hello, after running my Garnet for a while, the publish subscribe function will encounter this error

[FTL] [Session] ProcessMessages threw an exception:
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'GarnetTcpNetworkSender'.
   at Garnet.common.GarnetTcpNetworkSender.ThrowDisposed()
   at Garnet.server.RespServerSession.Publish(Byte*& keyPtr, Int32 keyLength, Byte*& valPtr, Int32 valLength, Byte*& inputPtr, Int32 sid)
   at Garnet.server.SubscribeBroker`3.Broadcast(Byte[] key, Byte* valPtr, Int32 valLength, Boolean ascii)
   at Garnet.server.RespServerSession.NetworkPUBLISH()
   at Garnet.server.RespServerSession.ProcessMessages()
   at Garnet.server.RespServerSession.TryConsumeMessages(Byte* reqBuffer, Int32 bytesReceived)

### Steps to reproduce the bug

After running for about 2 days, once this error occurs, the channel is blocked and unable to publish subscription messages

### Release version

v1.0.38

**Comment by badrishc** [comment]
Please try attached PR for a fix.
