### ISSUE TITLE
Linux version read crash

### ISSUE THREAD

**Issue by paul-duan** [microsoft/garnet#855]
### Describe the bug

Run Garnet 1.0.46 under kubuntu 24.04, write/read data from programs written in .NET on Windows, and when the data volume exceeds about 4000, Garnet crashes on Linux.
Garnet-server on Windows does not have this problem.

### Steps to reproduce the bug

1. Use .net to write an application to write data to garnet-server, about 30,000 pieces
2. Use .net to write a program that executes the key * command
3. garnet-server crashes

### Screenshots

The following is the information about the garnet-server crash on the Linux side:
(base) paul@S600:~/Tools/Database/KeyValue/Garnet/1.0.46$ ./GarnetServer 
    _________
   /_||___||_\      Garnet 1.0.46 64 bit; standalone mode
   '. \   / .'      Port: 6379
     '.\ /.'        https://aka.ms/GetGarnet
       '.'

* Ready to accept connections
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Buffer.Memmove(Byte ByRef, Byte ByRef, UIntPtr)
   at System.ReadOnlySpan`1[[System.Byte, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].CopyTo(System.Span`1<Byte>)
   at Garnet.common.RespWriteUtils.WriteBulkString(System.ReadOnlySpan`1<Byte>, Byte* ByRef, Byte*)
   at Garnet.server.RespServerSession.WriteOutputForScan(Int64, System.Collections.Generic.List`1<Byte[]>, Byte* ByRef, Byte*)
   at Garnet.server.RespServerSession.NetworkSCAN[[Garnet.server.GarnetApi`2[[Tsavorite.core.BasicContext`8[[Tsavorite.core.SpanByte, Tsavorite.core, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b],[Tsavorite.core.SpanByte, Tsavorite.core, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b],[Garnet.server.RawStringInput, Garnet.server, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b],[Tsavorite.core.SpanByteAndMemory, Tsavorite.core, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b],[System.Int64, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Garnet.server.MainSessionFunctions, Garnet.server, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b],[Tsavorite.core.StoreFunctions`4[[Tsavorite.core.SpanByte, Tsavorite.core, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b],[Tsavorite.core.SpanByte, Tsavorite.core, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b],[Tsavorite.core.SpanByteComparer, Tsavorite.core, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b],[Tsavorite.core.SpanByteRecordDisposer, Tsavorite.core, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b]], Tsavorite.core, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b],[Tsavorite.core.SpanByteAllocator`1[[Tsavorite.core.StoreFunctions`4[[Tsavorite.core.SpanByte, Tsavorite.core, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b],[Tsavorite.core.SpanByte, Tsavorite.core, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b],[Tsavorite.core.SpanByteComparer, Tsavorite.core, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b],[Tsavorite.core.SpanByteRecordDisposer, Tsavorite.core, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b]], Tsavorite.core, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b]], Tsavorite.core, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b]], Tsavorite.core, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b],[Tsavorite.core.BasicContext`8[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Garnet.server.ObjectInput, Garnet.server, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b],[Garnet.server.GarnetObjectStoreOutput, Garnet.server, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b],[System.Int64, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Garnet.server.ObjectSessionFunctions, Garnet.server, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b],[Tsavorite.core.StoreFunctions`4[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Tsavorite.core.DefaultRecordDisposer`2[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], Tsavorite.core, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b]], Tsavorite.core, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b],[Tsavorite.core.GenericAllocator`3[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Tsavorite.core.StoreFunctions`4[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Tsavorite.core.DefaultRecordDisposer`2[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], Tsavorite.core, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b]], Tsavorite.core, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b]], Tsavorite.core, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b]], Tsavorite.core, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b]], Garnet.server, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b]](Garnet.server.GarnetApi`2<Tsavorite.core.BasicContext`8<Tsavorite.core.SpanByte,Tsavorite.core.SpanByte,Garnet.server.RawStringInput,Tsavorite.core.SpanByteAndMemory,Int64,Garnet.server.MainSessionFunctions,Tsavorite.core.StoreFunctions`4<Tsavorite.core.SpanByte,Tsavorite.core.SpanByte,Tsavorite.core.SpanByteComparer,Tsavorite.core.SpanByteRecordDisposer>,Tsavorite.core.SpanByteAllocator`1<Tsavorite.core.StoreFunctions`4<Tsavorite.core.SpanByte,Tsavorite.core.SpanByte,Tsavorite.core.SpanByteComparer,Tsavorite.core.SpanByteRecordDisposer>>>,Tsavorite.core.BasicContext`8<System.__Canon,System.__Canon,Garnet.server.ObjectInput,Garnet.server.GarnetObjectStoreOutput,Int64,Garnet.server.ObjectSessionFunctions,Tsavorite.core.StoreFunctions`4<System.__Canon,System.__Canon,System.__Canon,Tsavorite.core.DefaultRecordDisposer`2<System.__Canon,System.__Canon>>,Tsavorite.core.GenericAllocator`3<System.__Canon,System.__Canon,Tsavorite.core.StoreFunctions`4<System.__Canon,System.__Canon,System.__Canon,Tsavorite.core.DefaultRecordDisposer`2<System.__Canon,System.__Canon>>>>> ByRef)
   at Garnet.server.RespServerSession.ProcessOtherCommands[[Garnet.server.GarnetApi`2[[Tsavorite.core.BasicContext`8[[Tsavorite.core.SpanByte, Tsavorite.core, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b],[Tsavorite.core.SpanByte, Tsavorite.core, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b],[Garnet.server.RawStringInput, Garnet.server, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b],[Tsavorite.core.SpanByteAndMemory, Tsavorite.core, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b],[System.Int64, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Garnet.server.MainSessionFunctions, Garnet.server, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b],[Tsavorite.core.StoreFunctions`4[[Tsavorite.core.SpanByte, Tsavorite.core, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b],[Tsavorite.core.SpanByte, Tsavorite.core, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b],[Tsavorite.core.SpanByteComparer, Tsavorite.core, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b],[Tsavorite.core.SpanByteRecordDisposer, Tsavorite.core, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b]], Tsavorite.core, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b],[Tsavorite.core.SpanByteAllocator`1[[Tsavorite.core.StoreFunctions`4[[Tsavorite.core.SpanByte, Tsavorite.core, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b],[Tsavorite.core.SpanByte, Tsavorite.core, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b],[Tsavorite.core.SpanByteComparer, Tsavorite.core, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b],[Tsavorite.core.SpanByteRecordDisposer, Tsavorite.core, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b]], Tsavorite.core, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b]], Tsavorite.core, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b]], Tsavorite.core, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b],[Tsavorite.core.BasicContext`8[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Garnet.server.ObjectInput, Garnet.server, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b],[Garnet.server.GarnetObjectStoreOutput, Garnet.server, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b],[System.Int64, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Garnet.server.ObjectSessionFunctions, Garnet.server, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b],[Tsavorite.core.StoreFunctions`4[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Tsavorite.core.DefaultRecordDisposer`2[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], Tsavorite.core, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b]], Tsavorite.core, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b],[Tsavorite.core.GenericAllocator`3[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Tsavorite.core.StoreFunctions`4[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Tsavorite.core.DefaultRecordDisposer`2[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], Tsavorite.core, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b]], Tsavorite.core, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b]], Tsavorite.core, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b]], Tsavorite.core, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b]], Garnet.server, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b]](Garnet.server.RespCommand, Garnet.server.GarnetApi`2<Tsavorite.core.BasicContext`8<Tsavorite.core.SpanByte,Tsavorite.core.SpanByte,Garnet.server.RawStringInput,Tsavorite.core.SpanByteAndMemory,Int64,Garnet.server.MainSessionFunctions,Tsavorite.core.StoreFunctions`4<Tsavorite.core.SpanByte,Tsavorite.core.SpanByte,Tsavorite.core.SpanByteComparer,Tsavorite.core.SpanByteRecordDisposer>,Tsavorite.core.SpanByteAllocator`1<Tsavorite.core.StoreFunctions`4<Tsavorite.core.SpanByte,Tsavorite.core.SpanByte,Tsavorite.core.SpanByteComparer,Tsavorite.core.SpanByteRecordDisposer>>>,Tsavorite.core.BasicContext`8<System.__Canon,System.__Canon,Garnet.server.ObjectInput,Garnet.server.GarnetObjectStoreOutput,Int64,Garnet.server.ObjectSessionFunctions,Tsavorite.core.StoreFunctions`4<System.__Canon,System.__Canon,System.__Canon,Tsavorite.core.DefaultRecordDisposer`2<System.__Canon,System.__Canon>>,Tsavorite.core.GenericAllocator`3<System.__Canon,System.__Canon,Tsavorite.core.StoreFunctions`4<System.__Canon,System.__Canon,System.__Canon,Tsavorite.core.DefaultRecordDisposer`2<System.__Canon,System.__Canon>>>>> ByRef)
   at Garnet.server.RespServerSession.ProcessArrayCommands[[Garnet.server.GarnetApi`2[[Tsavorite.core.BasicContext`8[[Tsavorite.core.SpanByte, Tsavorite.core, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b],[Tsavorite.core.SpanByte, Tsavorite.core, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b],[Garnet.server.RawStringInput, Garnet.server, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b],[Tsavorite.core.SpanByteAndMemory, Tsavorite.core, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b],[System.Int64, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Garnet.server.MainSessionFunctions, Garnet.server, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b],[Tsavorite.core.StoreFunctions`4[[Tsavorite.core.SpanByte, Tsavorite.core, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b],[Tsavorite.core.SpanByte, Tsavorite.core, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b],[Tsavorite.core.SpanByteComparer, Tsavorite.core, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b],[Tsavorite.core.SpanByteRecordDisposer, Tsavorite.core, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b]], Tsavorite.core, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b],[Tsavorite.core.SpanByteAllocator`1[[Tsavorite.core.StoreFunctions`4[[Tsavorite.core.SpanByte, Tsavorite.core, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b],[Tsavorite.core.SpanByte, Tsavorite.core, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b],[Tsavorite.core.SpanByteComparer, Tsavorite.core, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b],[Tsavorite.core.SpanByteRecordDisposer, Tsavorite.core, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b]], Tsavorite.core, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b]], Tsavorite.core, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b]], Tsavorite.core, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b],[Tsavorite.core.BasicContext`8[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Garnet.server.ObjectInput, Garnet.server, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b],[Garnet.server.GarnetObjectStoreOutput, Garnet.server, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b],[System.Int64, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Garnet.server.ObjectSessionFunctions, Garnet.server, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b],[Tsavorite.core.StoreFunctions`4[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Tsavorite.core.DefaultRecordDisposer`2[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], Tsavorite.core, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b]], Tsavorite.core, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b],[Tsavorite.core.GenericAllocator`3[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Tsavorite.core.StoreFunctions`4[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Tsavorite.core.DefaultRecordDisposer`2[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], Tsavorite.core, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b]], Tsavorite.core, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b]], Tsavorite.core, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b]], Tsavorite.core, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b]], Garnet.server, Version=1.0.46.0, Culture=neutral, PublicKeyToken=b93f59e18c9c8d6b]](Garnet.server.RespCommand, Garnet.server.GarnetApi`2<Tsavorite.core.BasicContext`8<Tsavorite.core.SpanByte,Tsavorite.core.SpanByte,Garnet.server.RawStringInput,Tsavorite.core.SpanByteAndMemory,Int64,Garnet.server.MainSessionFunctions,Tsavorite.core.StoreFunctions`4<Tsavorite.core.SpanByte,Tsavorite.core.SpanByte,Tsavorite.core.SpanByteComparer,Tsavorite.core.SpanByteRecordDisposer>,Tsavorite.core.SpanByteAllocator`1<Tsavorite.core.StoreFunctions`4<Tsavorite.core.SpanByte,Tsavorite.core.SpanByte,Tsavorite.core.SpanByteComparer,Tsavorite.core.SpanByteRecordDisposer>>>,Tsavorite.core.BasicContext`8<System.__Canon,System.__Canon,Garnet.server.ObjectInput,Garnet.server.GarnetObjectStoreOutput,Int64,Garnet.server.ObjectSessionFunctions,Tsavorite.core.StoreFunctions`4<System.__Canon,System.__Canon,System.__Canon,Tsavorite.core.DefaultRecordDisposer`2<System.__Canon,System.__Canon>>,Tsavorite.core.GenericAllocator`3<System.__Canon,System.__Canon,Tsavorite.core.StoreFunctions`4<System.__Canon,System.__Canon,System.__Canon,Tsavorite.core.DefaultRecordDisposer`2<System.__Canon,System.__Canon>>>>> ByRef)
   at Garnet.server.RespServerSession.ProcessMessages()
   at Garnet.server.RespServerSession.TryConsumeMessages(Byte*, Int32)
   at Garnet.networking.NetworkHandler`2[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].OnNetworkReceive(Int32)
   at Garnet.common.TcpNetworkHandlerBase`2[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].RecvEventArg_Completed(System.Object, System.Net.Sockets.SocketAsyncEventArgs)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Net.Sockets.SocketAsyncContext+BufferMemoryReceiveOperation.InvokeCallback(Boolean)
   at System.Net.Sockets.SocketAsyncEngine.System.Threading.IThreadPoolWorkItem.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
Aborted (core dumped)

### Release version

v1.0.46

### OS version

kunbunt24.04

**Comment by badrishc** [comment]
Can you provide a loading script as well, that will trigger the error exactly. Can't repro with the given information.
